# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813bb867c3b57892564ace9d5f983b7ba3a5921c71eb6b1a28c578247537c993cdbd546eb89358e974d6dcc3257f7b8368fdaaee1cdd1f2215a2fc0a45814883

test:
  secret_key_base: aa552f254bd9d75ceead23f9caf5deebdfc1ac032b040551fe35d4f18ce09b27fdade16a39796c5953d412fc875f60372c3ac1bcba39fa2430ba2ef398e4d73a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
